### ISSUE TITLE
latex: replace `\` in code text by `\textbackslash`

### ISSUE THREAD

**Issue by jschlatow** [nfeske/gosh#11]
Since `\` has a special meaning in tex, it must be replaced accordingly. Backslashes should not occur in normal writing but may occur  in code. I came across this issue when adding the RTC date/time format as inline code. Putting `'%Y-%m-%d %H:%M:%S\n'` into the txt file made latex choke on `\n`.

**Comment by jschlatow** [comment]
Fixed by 3e443ba.

**Comment by nfeske** [comment]
Thank you for the fix!
