### ISSUE TITLE
`[0]` inside inline verbatim text is considered a reference

### ISSUE THREAD

**Issue by jschlatow** [nfeske/gosh#7]
When formatting source code such as an array element as inline monospace text, it is wrongly considered a reference. This affects latex and html output.

**Comment by jschlatow** [comment]
Fixed by bf022a7 and a305a40

**Comment by nfeske** [comment]
This makes perfect sense. Thanks a lot! I merged both commits to master.

**Comment by nfeske** [comment]
I just updated the gosh submodule used by genodians.org via commit https://github.com/genodelabs/genodians.org/commit/8dac0b2c732f49232abee88cb83f60ce82dfcc02.

@cnuke, could you update genodians.org image?

**Comment by cnuke** [comment]
Done.
